### ISSUE TITLE
0.0.19 is now avaiable

### ISSUE THREAD

**Issue by beansmyname** [stellarhopper/discord-rpm-packaging#11]
I don´t know what´s going on over there at Chisel & Hammer, but 0.0.19 is the most up-to-date version now. 2 updates today :smile:

[deb](https://discordapp.com/api/download/canary?platform=linux)
[tar.gz](https://discordapp.com/api/download/canary?platform=linux&format=tar.gz)

**Comment by stellarhopper** [comment]
I've kicked off a build, should be up soon. Thanks!
