### ISSUE TITLE
0.0.21 available

### ISSUE THREAD

**Issue by hevanaa** [stellarhopper/discord-rpm-packaging#12]
Current installation doesn't work and won't update.

**Comment by hevanaa** [comment]
Latest version 0.0.20 seems to crash on Fedora 26, though. No relevant error message. 

> [Modules] Checking for host updates.
> [Modules] Host is up to date.
> [Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
> [Modules] No module updates available.
> [WebContents] crashed... reloading
> Feature redeclared; is this a duplicate flag?  voice_sound_stop_loop
> Feature redeclared; is this a duplicate flag?  voice_relative_sounds
> Feature redeclared; is this a duplicate flag?  voice_panning
> Feature redeclared; is this a duplicate flag?  voice_multiple_connections
> Feature redeclared; is this a duplicate flag?  media_devices
> Feature redeclared; is this a duplicate flag?  media_video

Guess we have to use 0.0.1 by now.

**Comment by hevanaa** [comment]
Reported to Discord.

**Comment by hevanaa** [comment]
0.0.21 fixed the problem

**Comment by stellarhopper** [comment]
Thanks for the ping/update. 0.0.21 is now up on copr.
