### ISSUE TITLE
0.0.23 available

### ISSUE THREAD

**Issue by J-Hill-Dev** [stellarhopper/discord-rpm-packaging#15]
[tar.gz (direct)](https://dl-canary.discordapp.net/apps/linux/0.0.23/discord-canary-0.0.23.tar.gz)
cheers

**Comment by bentalexanderhaase** [comment]
+1, thank you for making this repository!

**Comment by stellarhopper** [comment]
Update pushed to copr. Thanks @reportingsjr for the PR.
