### ISSUE TITLE
Failed update loop in-app on load

### ISSUE THREAD

**Issue by J-Hill-Dev** [stellarhopper/discord-rpm-packaging#17]
Discord tries to update itself automagically on start from the activity itself instead of telling us to download the new source. It's more inconvenient than the previous message telling us to download the source manually.

**Comment by seancallaway** [comment]
That's part of how Discord works, I'm afraid. It's not open-source so we can't modify it to not do that and/or give the option for an RPM.

**Comment by J-Hill-Dev** [comment]
It seems Discord fixed it. Thanks for the heads up.
