### ISSUE TITLE
Unable to find Copr repository

### ISSUE THREAD

**Issue by adrianbroher** [stellarhopper/discord-rpm-packaging#18]
Hi,

as far as I know this repository is the source for the Fedora Copr repository `vishalv-discord-canary`.  However `dnf` reports that it can't update the metadata for this repository anymore.  

```Failed to synchronize cache for repo 'vishalv-discord-canary', disabling.```

Also when visiting `https://copr.fedorainfracloud.org/coprs/vishalv/discord-canary/` the web server reports 404.

Seems like the infrastructure for this project was removed for whatever reason.  Maybe you want to investigate what happended there.

**Comment by wotmshuaisi** [comment]
wget https://copr.fedorainfracloud.org/coprs/morphy2k/discord-canary/repo/fedora-26/morphy2k-discord-canary-fedora-26.repo && sudo cp morphy2k-discord-canary-fedora-26.repo /etc/yum.repos.d/

**Comment by seancallaway** [comment]
It may have gotten pulled, as packaging proprietary apps in a Copr is against the terms of service (found out when my non-canary Copr was pulled).

**Comment by stellarhopper** [comment]
Yeah looks like it was pulled.. Guess I should really take the time to figure out a better solution :)
