### ISSUE TITLE
New verison available

### ISSUE THREAD

**Issue by robotmaxtron** [stellarhopper/discord-rpm-packaging#2]
There is a new version available, hoping to get that updated into the repo as well as a Fedora25 repo.

**Comment by stellarhopper** [comment]
Thanks, I've enabled F25 in copr, and rebuilt 0.0.9 to include that, and am testing out 0.0.10 locally. Once everything works, I'll kick of a copr build for it shortly here.

**Comment by robotmaxtron** [comment]
I just installed the 0.0.10 version from the copr repo on F25 and it seems to be working well. Thank you!
