### ISSUE TITLE
Update.

### ISSUE THREAD

**Issue by sustained** [stellarhopper/discord-rpm-packaging#4]
Will this be updated to the latest version (0.0.13 as of today, I believe)?

**Comment by losuler** [comment]
If you need it sooner you can easily modify the version number and build the package yourself. Alternatively you can even more easily download the [0.013 tarball](https://dl-canary.discordapp.net/apps/linux/0.0.13/discord-canary-0.0.13.tar.gz) and just run it from the extracted directory.

**Comment by sustained** [comment]
Yeah, I have just been running it myself from the extracted tarball up until now.

Looks like someone has very recently submitted a pull request for 0.0.13. I didn't realise it was simply a matter of changing the version number else I probably would have done it myself.

Thanks for the reply.

**Comment by seancallaway** [comment]
There's a _tiny_ bit more that has to be done (unpack the tarball, replace the provided `.desktop` file with the one in this repo, and rebuild the SRPM), but not a lot. This repo is really just for the .spec and .desktop files, which are quite important, but not all of the setup.

**Comment by stellarhopper** [comment]
Build should be ready in COPR now, and works on my system :)

**Comment by sustained** [comment]
Okay but we are now on 0.0.15. If you don't have time to keep this thing up to date then how do you feel about giving someone else, who does have time, access to the repository?

**Comment by Sadb0ys** [comment]
As sustained mentioned, I'd love an update for 0.0.15 - Can't seem to build it myself.

**Comment by seancallaway** [comment]
@sustained Any reason you're not on the non-Canary official build?

**Comment by Sadb0ys** [comment]
@seancallaway How do I build it officially? I'm on Fedora, whenever I try to install discord-canary it pulls an old version.

**Comment by seancallaway** [comment]
`discord-canary` will always be the development, or non-official, release. Discord 0.0.1 is available via their [downloads page](https://discordapp.com/download) or [my Copr](https://copr.fedorainfracloud.org/coprs/seancallaway/discord/). I'm trying to convince the Discord folks to let me package it in RPMFusion, but they want to keep packaging in house, so it's an uphill battle.

**Comment by stellarhopper** [comment]
Hey guys, sorry I've been travelling and hadn't had a chance to look at this. I'm using discord much less than I used to, so this has somewhat fallen into neglect. I'm happy to update the copr now, or if it seems like the better option, redirect everyone to @seancallaway 's copr (we probably want the stable one anyway), and deprecate mine.

**Comment by seancallaway** [comment]
I'd recommend you keep yours going @stellarhopper for the discord-canary build and mine can be left just for the non-canary releases. Up to you.

**Comment by stellarhopper** [comment]
Fair enough, I'll update it.
