### ISSUE TITLE
0.0.15 Update

### ISSUE THREAD

**Issue by wescrockett** [stellarhopper/discord-rpm-packaging#7]
Current build cannot connect to Discord servers. Package needs to be updated with 0.0.15 build.

**Comment by seancallaway** [comment]
Might want to take a look at #4. I'm not sure that @stellarhopper has time to devote to this, but there are other options available to you.

**Comment by wescrockett** [comment]
Thanks Sean. I'll check it out.

**Comment by stellarhopper** [comment]
I've updated the repo and COPR to 0.0.15. Also added a script to make the whole process much easier. @seancallaway you might be able to reuse it for the stable version.
